#!/bin/bash
set -e

# Check arguments
if [ -z "${1}" ]; then
    echo "Usage: build <nginx_version>"
    exit 1
fi

# Configure versions
NGINX_VERSION="${1}"
ZLIB_VERSION='1.2.8'
PCRE_VERSION='8.37'
UPLOAD_PROGRESS_VERSION='0.9.1'
CACHE_PURGE_VERSION='2.3'

# package names
pkg=nginx-${NGINX_VERSION}.tar.gz
pkg_pcre=pcre-${PCRE_VERSION}.tar.bz2
pkg_zlib=zlib-${ZLIB_VERSION}.tar.gz
pkg_upload_progress=nginx-upload-progress-module-${UPLOAD_PROGRESS_VERSION}.tar.gz
pkg_cache_purge=ngx_cache_purge-${CACHE_PURGE_VERSION}.tar.gz

# Import utils
source build_util

# Prepare build enviroment
CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
BUILD_DIR="${CURRENT_DIR}/tmp"
TARGET_DIR="$(dirname "${CURRENT_DIR}")/nginx-${NGINX_VERSION}"

if [ -d "${TARGET_DIR}" ]; then
    rm -rf "${TARGET_DIR}"
fi

mkdir -p ${BUILD_DIR}
pushd ${BUILD_DIR}

# Get packages
download_and_unpack ${pkg_pcre} ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/${pkg_pcre}
download_and_unpack ${pkg_zlib} http://zlib.net/${pkg_zlib}
download_and_unpack ${pkg_upload_progress} https://github.com/masterzen/nginx-upload-progress-module/archive/v${UPLOAD_PROGRESS_VERSION}.tar.gz
download_and_unpack ${pkg_cache_purge} https://github.com/FRiCKLE/ngx_cache_purge/archive/${CACHE_PURGE_VERSION}.tar.gz
download_and_unpack ${pkg} http://nginx.org/download/${pkg}

# Go to source
pushd nginx-${NGINX_VERSION}

# Configuring nginx
./configure \
    --with-zlib=${BUILD_DIR}/zlib-${ZLIB_VERSION} \
    --with-pcre=${BUILD_DIR}/pcre-${PCRE_VERSION} \
    --with-http_realip_module \
    --with-http_gzip_static_module \
    --with-http_stub_status_module \
    --without-http_proxy_module \
    --without-mail_pop3_module \
    --without-mail_smtp_module \
    --without-mail_imap_module \
    --without-http_uwsgi_module \
    --without-http_scgi_module \
    --without-http_memcached_module \
    --without-http_userid_module \
    --without-http_ssi_module \
    --without-http_split_clients_module \
    --without-http_browser_module \
    --without-http_charset_module \
    --without-http_empty_gif_module \
    --without-http_upstream_ip_hash_module \
    --without-http_upstream_least_conn_module \
	 --add-module=${BUILD_DIR}/nginx-upload-progress-module-${UPLOAD_PROGRESS_VERSION} \
	 --add-module=${BUILD_DIR}/ngx_cache_purge-${CACHE_PURGE_VERSION} \
    --prefix=${TARGET_DIR}

# Compiling nginx
make install

# Clean build enviroment
popd
popd
rm -rf ${BUILD_DIR}

exit 0
